version: '3.8'

services:
  # Наш сервис базы данных
  mongodb:
    image: mongo:latest
    container_name: auth-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: