version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_hw9
    restart: always
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3307:3306'
